module.exports = {
  CONNECT_USER: 'CONNECT_USER',
  GET_MESSAGES: 'GET_MESSAGES',
  GET_ALL_MESSAGES: 'GET_ALL_MESSAGES',
  NEW_MESSAGE: 'NEW_MESSAGE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  GET_CHAT: 'GET_CHAT',
  GET_ALL_CHATS: 'GET_ALL_CHATS',
  SEND_CHATS: 'SEND_CHATS',
  SEND_CHAT: 'SEND_CHAT',
}
